# Generated by Django 5.0.6 on 2024-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_rename_profession_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='building_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='building_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='building_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='room_number_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='room_number_ky',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='room_number_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkhomework',
            name='feedback_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkhomework',
            name='feedback_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkhomework',
            name='feedback_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkhomework',
            name='grade_en',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='checkhomework',
            name='grade_ky',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='checkhomework',
            name='grade_ru',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_ky',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ky',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='bio_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='title_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationcourse',
            name='grade_en',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='registrationcourse',
            name='grade_ky',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='registrationcourse',
            name='grade_ru',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
